module.exports = {
  extends: ["airbnb-typescript-prettier"],
  rules: {
    camelcase: 0,
    "no-console": 0,
    "@typescript-eslint/no-use-before-define": 0,
    "@typescript-eslint/explicit-module-boundary-types": 0,
    "no-shadow": 0,
    "no-restricted-globals": 0,
    "jsx-a11y/control-has-associated-label": 0,
    "no-nested-ternary": 0,
    "import/no-named-as-default": 0,
    "import/prefer-default-export": 0,
    "no-prototype-builtins": 0,
    "consistent-return": 0,
    "@typescript-eslint/no-unused-vars": 0,
    "no-unused-expressions": 0,
    "no-restricted-syntax": 0,
    "prefer-destructuring": 1,
    "no-return-await": 1,
    "import/extensions": 1,
    "prefer-const": 0,
    "no-param-reassign": 0,
    "import/no-extraneous-dependencies": 0,
    "@typescript-eslint/ban-ts-ignore": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "no-underscore-dangle": 0,
    "no-alert": 0,
    "@typescript-eslint/no-var-requires": 0,
    quotes: ["error", "double"],
  },
};
